apiVersion: v1
kind: Service
metadata:
  name: ctf-{{ .Values.chalName }}-service
spec:
  type: NodePort
  selector:
    app: ctf-{{ .Values.chalName }}
  ports:
    - port: 80
      targetPort: docker-port
      nodePort: 0