apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctfd-frontend
spec:
  maxReplicas: 9
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctfd-frontend-deployment
  targetCPUUtilizationPercentage: 60
